# Generated by Django 4.1.3 on 2023-07-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0004_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
