# Generated by Django 4.2.6 on 2023-11-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0008_user_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='news_pics/')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(to='GenzApp.image'),
        ),
    ]
