# Generated by Django 4.2.6 on 2023-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0009_image_remove_news_image_news_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='news_pics/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='news_pics/'),
        ),
    ]
