# Generated by Django 4.2.6 on 2023-11-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0010_remove_news_images_news_image1_news_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image2',
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='default.png', null=True, upload_to='news_pics/')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('intro', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenzApp.authors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenzApp.category')),
            ],
        ),
    ]
