# Generated by Django 4.2.6 on 2023-11-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0011_remove_news_image2_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('One Year', 'One Year'), ('One Year with print', 'One Year with print')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
