# Generated by Django 4.2.6 on 2023-11-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0012_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('A YEAR', 'A YEAR'), ('A YEAR WITH PRINT', 'A YEAR WITH PRINT')], max_length=20),
        ),
    ]
