# Generated by Django 4.2.6 on 2023-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0013_remove_user_username_alter_subscriptionplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
