# Generated by Django 4.2.6 on 2023-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0016_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
    ]
