# Generated by Django 4.2.6 on 2023-11-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0017_rename_image1_news_image_remove_newsletter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
