# Generated by Django 4.2.6 on 2023-11-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0018_newsletter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='image1',
            new_name='image',
        ),
    ]
