# Generated by Django 4.2.6 on 2023-11-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenzApp', '0019_rename_image1_stories_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
